### ISSUE TITLE
Internal Error on /dc skillinfo Command

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#73] opened 2018-02-28 08:32 UTC
Hello. I'm getting this new one:

https://pastebin.com/raw/BuQ7rE1D

Thoughts?

**Comment by drekryan** [comment] 2018-02-28 08:51
This error seems to be caused by an error in our error handling which I can patch. However it was trying to throw an exception because the DwarfPlayer data couldn't be fetched. So for some reason it was unable to "find" your player data. Ill have to dig deeper to try to understand how you ran into this error.

**Comment by drekryan** [comment] 2018-02-28 09:47
This particular crash should be fixed as of commit cc36e6f7939cc89a6e8b56573839485d77649af2

The skillinfo command could use further improvements to its command parsing but it shouldn't crash any longer in this case.

**Closed as completed by drekryan** 2018-02-28 09:47 UTC
